//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SudoKu.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SudoKu.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 © 2026 天王软件工作室 的本地化字符串。
        /// </summary>
        internal static string App_Copyright {
            get {
                return ResourceManager.GetString("App_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数独合集 的本地化字符串。
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 1.0 的本地化字符串。
        /// </summary>
        internal static string App_Version {
            get {
                return ResourceManager.GetString("App_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回主菜单 的本地化字符串。
        /// </summary>
        internal static string Button_BackToMenu {
            get {
                return ResourceManager.GetString("Button_BackToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除统计数据 的本地化字符串。
        /// </summary>
        internal static string Button_ClearStatistics {
            get {
                return ResourceManager.GetString("Button_ClearStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载游戏 的本地化字符串。
        /// </summary>
        internal static string Button_ContinueGame {
            get {
                return ResourceManager.GetString("Button_ContinueGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义游戏 的本地化字符串。
        /// </summary>
        internal static string Button_CustomGame {
            get {
                return ResourceManager.GetString("Button_CustomGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 擦除 的本地化字符串。
        /// </summary>
        internal static string Button_Erase {
            get {
                return ResourceManager.GetString("Button_Erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Button_Hint {
            get {
                return ResourceManager.GetString("Button_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载游戏 的本地化字符串。
        /// </summary>
        internal static string Button_LoadGame {
            get {
                return ResourceManager.GetString("Button_LoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 笔记 的本地化字符串。
        /// </summary>
        internal static string Button_Notes {
            get {
                return ResourceManager.GetString("Button_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再玩一次 的本地化字符串。
        /// </summary>
        internal static string Button_PlayAgain {
            get {
                return ResourceManager.GetString("Button_PlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重做 的本地化字符串。
        /// </summary>
        internal static string Button_Redo {
            get {
                return ResourceManager.GetString("Button_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解答 的本地化字符串。
        /// </summary>
        internal static string Button_Solution {
            get {
                return ResourceManager.GetString("Button_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始新游戏 的本地化字符串。
        /// </summary>
        internal static string Button_StartNewGame {
            get {
                return ResourceManager.GetString("Button_StartNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销 的本地化字符串。
        /// </summary>
        internal static string Button_Undo {
            get {
                return ResourceManager.GetString("Button_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证 的本地化字符串。
        /// </summary>
        internal static string Button_Validate {
            get {
                return ResourceManager.GetString("Button_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Common_Button_OK {
            get {
                return ResourceManager.GetString("Common_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准确率 的本地化字符串。
        /// </summary>
        internal static string Completion_Accuracy {
            get {
                return ResourceManager.GetString("Completion_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回首页 的本地化字符串。
        /// </summary>
        internal static string Completion_BackToHome {
            get {
                return ResourceManager.GetString("Completion_BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最佳成绩 的本地化字符串。
        /// </summary>
        internal static string Completion_BestScore {
            get {
                return ResourceManager.GetString("Completion_BestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前 的本地化字符串。
        /// </summary>
        internal static string Completion_Current {
            get {
                return ResourceManager.GetString("Completion_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 难度 的本地化字符串。
        /// </summary>
        internal static string Completion_Difficulty {
            get {
                return ResourceManager.GetString("Completion_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误次数 的本地化字符串。
        /// </summary>
        internal static string Completion_ErrorCount {
            get {
                return ResourceManager.GetString("Completion_ErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏类型 的本地化字符串。
        /// </summary>
        internal static string Completion_GameType {
            get {
                return ResourceManager.GetString("Completion_GameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新纪录! 的本地化字符串。
        /// </summary>
        internal static string Completion_NewRecordMessage {
            get {
                return ResourceManager.GetString("Completion_NewRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谜题已完成 的本地化字符串。
        /// </summary>
        internal static string Completion_PuzzleCompleted {
            get {
                return ResourceManager.GetString("Completion_PuzzleCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连胜 的本地化字符串。
        /// </summary>
        internal static string Completion_Streak {
            get {
                return ResourceManager.GetString("Completion_Streak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用时 的本地化字符串。
        /// </summary>
        internal static string Completion_TimeUsed {
            get {
                return ResourceManager.GetString("Completion_TimeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看统计 的本地化字符串。
        /// </summary>
        internal static string Completion_ViewStatistics {
            get {
                return ResourceManager.GetString("Completion_ViewStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string CustomGame_Clear {
            get {
                return ResourceManager.GetString("CustomGame_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已填 的本地化字符串。
        /// </summary>
        internal static string CustomGame_FilledCells {
            get {
                return ResourceManager.GetString("CustomGame_FilledCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余 的本地化字符串。
        /// </summary>
        internal static string CustomGame_RemainingCells {
            get {
                return ResourceManager.GetString("CustomGame_RemainingCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string CustomGame_Save {
            get {
                return ResourceManager.GetString("CustomGame_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始游戏 的本地化字符串。
        /// </summary>
        internal static string CustomGame_StartGame {
            get {
                return ResourceManager.GetString("CustomGame_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证 的本地化字符串。
        /// </summary>
        internal static string CustomGame_Validate {
            get {
                return ResourceManager.GetString("CustomGame_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入门 的本地化字符串。
        /// </summary>
        internal static string Difficulty_Beginner {
            get {
                return ResourceManager.GetString("Difficulty_Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        internal static string Difficulty_Custom {
            get {
                return ResourceManager.GetString("Difficulty_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简单 的本地化字符串。
        /// </summary>
        internal static string Difficulty_Easy {
            get {
                return ResourceManager.GetString("Difficulty_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专家 的本地化字符串。
        /// </summary>
        internal static string Difficulty_Expert {
            get {
                return ResourceManager.GetString("Difficulty_Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 困难 的本地化字符串。
        /// </summary>
        internal static string Difficulty_Hard {
            get {
                return ResourceManager.GetString("Difficulty_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 难度 的本地化字符串。
        /// </summary>
        internal static string Difficulty_Label {
            get {
                return ResourceManager.GetString("Difficulty_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大师 的本地化字符串。
        /// </summary>
        internal static string Difficulty_Master {
            get {
                return ResourceManager.GetString("Difficulty_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中等 的本地化字符串。
        /// </summary>
        internal static string Difficulty_Medium {
            get {
                return ResourceManager.GetString("Difficulty_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最佳 的本地化字符串。
        /// </summary>
        internal static string Game_BestTime {
            get {
                return ResourceManager.GetString("Game_BestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成度 的本地化字符串。
        /// </summary>
        internal static string Game_CompletionPercentage {
            get {
                return ResourceManager.GetString("Game_CompletionPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜完成! 的本地化字符串。
        /// </summary>
        internal static string Game_Congratulations {
            get {
                return ResourceManager.GetString("Game_Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用时 的本地化字符串。
        /// </summary>
        internal static string Game_ElapsedTime {
            get {
                return ResourceManager.GetString("Game_ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏结束 的本地化字符串。
        /// </summary>
        internal static string Game_GameOver {
            get {
                return ResourceManager.GetString("Game_GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在生成谜题... 的本地化字符串。
        /// </summary>
        internal static string Game_GeneratingPuzzle {
            get {
                return ResourceManager.GetString("Game_GeneratingPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Game_Mistakes {
            get {
                return ResourceManager.GetString("Game_Mistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新纪录! 的本地化字符串。
        /// </summary>
        internal static string Game_NewRecord {
            get {
                return ResourceManager.GetString("Game_NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已暂停 的本地化字符串。
        /// </summary>
        internal static string Game_Paused {
            get {
                return ResourceManager.GetString("Game_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义数独 的本地化字符串。
        /// </summary>
        internal static string GameType_Custom {
            get {
                return ResourceManager.GetString("GameType_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建和编辑您自己的数独谜题 的本地化字符串。
        /// </summary>
        internal static string GameType_Custom_Desc {
            get {
                return ResourceManager.GetString("GameType_Custom_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对角线数独 的本地化字符串。
        /// </summary>
        internal static string GameType_Diagonal {
            get {
                return ResourceManager.GetString("GameType_Diagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在标准数独基础上增加对角线约束，两条主对角线也需填入1-9且不重复 的本地化字符串。
        /// </summary>
        internal static string GameType_Diagonal_Desc {
            get {
                return ResourceManager.GetString("GameType_Diagonal_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锯齿数独 的本地化字符串。
        /// </summary>
        internal static string GameType_Jigsaw {
            get {
                return ResourceManager.GetString("GameType_Jigsaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不规则宫格数独，宫格形状为锯齿形而非标准3x3方块 的本地化字符串。
        /// </summary>
        internal static string GameType_Jigsaw_Desc {
            get {
                return ResourceManager.GetString("GameType_Jigsaw_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀手数独 的本地化字符串。
        /// </summary>
        internal static string GameType_Killer {
            get {
                return ResourceManager.GetString("GameType_Killer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无初始数字，通过笼子区域的数字之和提示来推理填入数字 的本地化字符串。
        /// </summary>
        internal static string GameType_Killer_Desc {
            get {
                return ResourceManager.GetString("GameType_Killer_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 武士数独 的本地化字符串。
        /// </summary>
        internal static string GameType_Samurai {
            get {
                return ResourceManager.GetString("GameType_Samurai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 五个9x9数独重叠组成的大型谜题，极具挑战性 的本地化字符串。
        /// </summary>
        internal static string GameType_Samurai_Desc {
            get {
                return ResourceManager.GetString("GameType_Samurai_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准数独 的本地化字符串。
        /// </summary>
        internal static string GameType_Standard {
            get {
                return ResourceManager.GetString("GameType_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经典9x9数独，每行、每列和每个3x3宫格内填入1-9且不重复 的本地化字符串。
        /// </summary>
        internal static string GameType_Standard_Desc {
            get {
                return ResourceManager.GetString("GameType_Standard_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口数独 的本地化字符串。
        /// </summary>
        internal static string GameType_Window {
            get {
                return ResourceManager.GetString("GameType_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在标准数独基础上增加四个窗口区域约束，窗口内数字也需不重复 的本地化字符串。
        /// </summary>
        internal static string GameType_Window_Desc {
            get {
                return ResourceManager.GetString("GameType_Window_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对角线也需填满1-9 的本地化字符串。
        /// </summary>
        internal static string GameTypeDiagonalDescription {
            get {
                return ResourceManager.GetString("GameTypeDiagonalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不规则区域形状 的本地化字符串。
        /// </summary>
        internal static string GameTypeJigsawDescription {
            get {
                return ResourceManager.GetString("GameTypeJigsawDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 笼子求和约束 的本地化字符串。
        /// </summary>
        internal static string GameTypeKillerDescription {
            get {
                return ResourceManager.GetString("GameTypeKillerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 五个重叠的9x9网格 的本地化字符串。
        /// </summary>
        internal static string GameTypeSamuraiDescription {
            get {
                return ResourceManager.GetString("GameTypeSamuraiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经典9x9数独，标准规则 的本地化字符串。
        /// </summary>
        internal static string GameTypeStandardDescription {
            get {
                return ResourceManager.GetString("GameTypeStandardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四个额外窗口区域 的本地化字符串。
        /// </summary>
        internal static string GameTypeWindowDescription {
            get {
                return ResourceManager.GetString("GameTypeWindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在应用变换... 的本地化字符串。
        /// </summary>
        internal static string Gen_ApplyingSubstitution {
            get {
                return ResourceManager.GetString("Gen_ApplyingSubstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成完成 的本地化字符串。
        /// </summary>
        internal static string Gen_Completed {
            get {
                return ResourceManager.GetString("Gen_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在创建区域... 的本地化字符串。
        /// </summary>
        internal static string Gen_CreatingRegions {
            get {
                return ResourceManager.GetString("Gen_CreatingRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在生成谜题... 的本地化字符串。
        /// </summary>
        internal static string Gen_DiggingPuzzle {
            get {
                return ResourceManager.GetString("Gen_DiggingPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成失败 的本地化字符串。
        /// </summary>
        internal static string Gen_Failed {
            get {
                return ResourceManager.GetString("Gen_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成{0}数独{1}级游戏失败，请稍后重试！ 的本地化字符串。
        /// </summary>
        internal static string Gen_FailedMessage {
            get {
                return ResourceManager.GetString("Gen_FailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在生成解答... 的本地化字符串。
        /// </summary>
        internal static string Gen_GeneratingSolution {
            get {
                return ResourceManager.GetString("Gen_GeneratingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在初始化... 的本地化字符串。
        /// </summary>
        internal static string Gen_Initializing {
            get {
                return ResourceManager.GetString("Gen_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载模板... 的本地化字符串。
        /// </summary>
        internal static string Gen_LoadingTemplate {
            get {
                return ResourceManager.GetString("Gen_LoadingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户取消 的本地化字符串。
        /// </summary>
        internal static string Gen_UserCancelled {
            get {
                return ResourceManager.GetString("Gen_UserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证谜题... 的本地化字符串。
        /// </summary>
        internal static string Gen_Validating {
            get {
                return ResourceManager.GetString("Gen_Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择难度 的本地化字符串。
        /// </summary>
        internal static string Home_SelectDifficulty {
            get {
                return ResourceManager.GetString("Home_SelectDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择游戏类型 的本地化字符串。
        /// </summary>
        internal static string Home_SelectGameType {
            get {
                return ResourceManager.GetString("Home_SelectGameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        internal static string Language_Chinese {
            get {
                return ResourceManager.GetString("Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要清除所有统计数据吗？此操作不可撤销。 的本地化字符串。
        /// </summary>
        internal static string Msg_ConfirmClearStats {
            get {
                return ResourceManager.GetString("Msg_ConfirmClearStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除此存档吗？ 的本地化字符串。
        /// </summary>
        internal static string Msg_ConfirmDeleteSave {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏已保存 的本地化字符串。
        /// </summary>
        internal static string Msg_GameSaved {
            get {
                return ResourceManager.GetString("Msg_GameSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已使用提示 的本地化字符串。
        /// </summary>
        internal static string Msg_HintUsed {
            get {
                return ResourceManager.GetString("Msg_HintUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谜题无效，请检查输入 的本地化字符串。
        /// </summary>
        internal static string Msg_InvalidPuzzle {
            get {
                return ResourceManager.GetString("Msg_InvalidPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有更多提示了 的本地化字符串。
        /// </summary>
        internal static string Msg_NoMoreHints {
            get {
                return ResourceManager.GetString("Msg_NoMoreHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到已保存的游戏 的本地化字符串。
        /// </summary>
        internal static string Msg_NoSavedGame {
            get {
                return ResourceManager.GetString("Msg_NoSavedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谜题已完成 的本地化字符串。
        /// </summary>
        internal static string Msg_PuzzleComplete {
            get {
                return ResourceManager.GetString("Msg_PuzzleComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Page_Completion {
            get {
                return ResourceManager.GetString("Page_Completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义游戏 的本地化字符串。
        /// </summary>
        internal static string Page_CustomGame {
            get {
                return ResourceManager.GetString("Page_CustomGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 的本地化字符串。
        /// </summary>
        internal static string Page_Game {
            get {
                return ResourceManager.GetString("Page_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数独合集 的本地化字符串。
        /// </summary>
        internal static string Page_Home {
            get {
                return ResourceManager.GetString("Page_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则 的本地化字符串。
        /// </summary>
        internal static string Page_Rules {
            get {
                return ResourceManager.GetString("Page_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Page_Settings {
            get {
                return ResourceManager.GetString("Page_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计 的本地化字符串。
        /// </summary>
        internal static string Page_Statistics {
            get {
                return ResourceManager.GetString("Page_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则介绍 的本地化字符串。
        /// </summary>
        internal static string Rules_Description {
            get {
                return ResourceManager.GetString("Rules_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对角线数独规则 的本地化字符串。
        /// </summary>
        internal static string Rules_Diagonal_Title {
            get {
                return ResourceManager.GetString("Rules_Diagonal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锯齿数独规则 的本地化字符串。
        /// </summary>
        internal static string Rules_Jigsaw_Title {
            get {
                return ResourceManager.GetString("Rules_Jigsaw_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀手数独规则 的本地化字符串。
        /// </summary>
        internal static string Rules_Killer_Title {
            get {
                return ResourceManager.GetString("Rules_Killer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 武士数独规则 的本地化字符串。
        /// </summary>
        internal static string Rules_Samurai_Title {
            get {
                return ResourceManager.GetString("Rules_Samurai_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准数独是最经典的数独变体 的本地化字符串。
        /// </summary>
        internal static string Rules_Standard_Description {
            get {
                return ResourceManager.GetString("Rules_Standard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准数独规则 的本地化字符串。
        /// </summary>
        internal static string Rules_Standard_Title {
            get {
                return ResourceManager.GetString("Rules_Standard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏规则 的本地化字符串。
        /// </summary>
        internal static string Rules_Title {
            get {
                return ResourceManager.GetString("Rules_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口数独规则 的本地化字符串。
        /// </summary>
        internal static string Rules_Window_Title {
            get {
                return ResourceManager.GetString("Rules_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级设置 的本地化字符串。
        /// </summary>
        internal static string Settings_AdvancedSettings {
            get {
                return ResourceManager.GetString("Settings_AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级策略提示 的本地化字符串。
        /// </summary>
        internal static string Settings_AdvancedStrategy {
            get {
                return ResourceManager.GetString("Settings_AdvancedStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音频设置 的本地化字符串。
        /// </summary>
        internal static string Settings_Audio {
            get {
                return ResourceManager.GetString("Settings_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动错误检查 的本地化字符串。
        /// </summary>
        internal static string Settings_AutoCheckErrors {
            get {
                return ResourceManager.GetString("Settings_AutoCheckErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动笔记模式 的本地化字符串。
        /// </summary>
        internal static string Settings_AutoMarkMode {
            get {
                return ResourceManager.GetString("Settings_AutoMarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景音乐 的本地化字符串。
        /// </summary>
        internal static string Settings_BackgroundMusic {
            get {
                return ResourceManager.GetString("Settings_BackgroundMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础设置 的本地化字符串。
        /// </summary>
        internal static string Settings_BasicSettings {
            get {
                return ResourceManager.GetString("Settings_BasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 候选数设置 的本地化字符串。
        /// </summary>
        internal static string Settings_CandidateSettings {
            get {
                return ResourceManager.GetString("Settings_CandidateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用背景音乐 的本地化字符串。
        /// </summary>
        internal static string Settings_EnableBackgroundMusic {
            get {
                return ResourceManager.GetString("Settings_EnableBackgroundMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用音效 的本地化字符串。
        /// </summary>
        internal static string Settings_EnableSoundEffects {
            get {
                return ResourceManager.GetString("Settings_EnableSoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误高亮 的本地化字符串。
        /// </summary>
        internal static string Settings_ErrorHighlight {
            get {
                return ResourceManager.GetString("Settings_ErrorHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏设置 的本地化字符串。
        /// </summary>
        internal static string Settings_GameSettings {
            get {
                return ResourceManager.GetString("Settings_GameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏设置 的本地化字符串。
        /// </summary>
        internal static string Settings_GameSettingsLabel {
            get {
                return ResourceManager.GetString("Settings_GameSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联单元格高亮 的本地化字符串。
        /// </summary>
        internal static string Settings_HighlightRelatedCells {
            get {
                return ResourceManager.GetString("Settings_HighlightRelatedCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相同数字高亮 的本地化字符串。
        /// </summary>
        internal static string Settings_HighlightSameNumbers {
            get {
                return ResourceManager.GetString("Settings_HighlightSameNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高亮设置 的本地化字符串。
        /// </summary>
        internal static string Settings_HighlightSettings {
            get {
                return ResourceManager.GetString("Settings_HighlightSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置 的本地化字符串。
        /// </summary>
        internal static string Settings_SaveSettings {
            get {
                return ResourceManager.GetString("Settings_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择语言 的本地化字符串。
        /// </summary>
        internal static string Settings_SelectLanguage {
            get {
                return ResourceManager.GetString("Settings_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择主题 的本地化字符串。
        /// </summary>
        internal static string Settings_SelectTheme {
            get {
                return ResourceManager.GetString("Settings_SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示计时器 的本地化字符串。
        /// </summary>
        internal static string Settings_ShowTimer {
            get {
                return ResourceManager.GetString("Settings_ShowTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音效 的本地化字符串。
        /// </summary>
        internal static string Settings_SoundEffects {
            get {
                return ResourceManager.GetString("Settings_SoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        internal static string Settings_SystemSettings {
            get {
                return ResourceManager.GetString("Settings_SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音量 的本地化字符串。
        /// </summary>
        internal static string Settings_Volume {
            get {
                return ResourceManager.GetString("Settings_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均时间 的本地化字符串。
        /// </summary>
        internal static string Stats_AvgTime {
            get {
                return ResourceManager.GetString("Stats_AvgTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最佳连胜 的本地化字符串。
        /// </summary>
        internal static string Stats_BestStreak {
            get {
                return ResourceManager.GetString("Stats_BestStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最佳时间 的本地化字符串。
        /// </summary>
        internal static string Stats_BestTime {
            get {
                return ResourceManager.GetString("Stats_BestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最佳连胜 的本地化字符串。
        /// </summary>
        internal static string Stats_BestWinStreak {
            get {
                return ResourceManager.GetString("Stats_BestWinStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对比 的本地化字符串。
        /// </summary>
        internal static string Stats_Comparison {
            get {
                return ResourceManager.GetString("Stats_Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前连胜 的本地化字符串。
        /// </summary>
        internal static string Stats_CurrentStreak {
            get {
                return ResourceManager.GetString("Stats_CurrentStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前连胜 的本地化字符串。
        /// </summary>
        internal static string Stats_CurrentWinStreak {
            get {
                return ResourceManager.GetString("Stats_CurrentWinStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 各游戏类型详细统计 的本地化字符串。
        /// </summary>
        internal static string Stats_DetailedDescription {
            get {
                return ResourceManager.GetString("Stats_DetailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详情 的本地化字符串。
        /// </summary>
        internal static string Stats_Details {
            get {
                return ResourceManager.GetString("Stats_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏: {0} 的本地化字符串。
        /// </summary>
        internal static string Stats_Games {
            get {
                return ResourceManager.GetString("Stats_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏次数 的本地化字符串。
        /// </summary>
        internal static string Stats_GamesPlayed {
            get {
                return ResourceManager.GetString("Stats_GamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏: {0} 的本地化字符串。
        /// </summary>
        internal static string Stats_GamesPlayedFormat {
            get {
                return ResourceManager.GetString("Stats_GamesPlayedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胜利次数 的本地化字符串。
        /// </summary>
        internal static string Stats_GamesWon {
            get {
                return ResourceManager.GetString("Stats_GamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胜利: {0} 的本地化字符串。
        /// </summary>
        internal static string Stats_GamesWonFormat {
            get {
                return ResourceManager.GetString("Stats_GamesWonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 各游戏类型详细统计 的本地化字符串。
        /// </summary>
        internal static string Stats_GameTypeStats {
            get {
                return ResourceManager.GetString("Stats_GameTypeStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏次数 的本地化字符串。
        /// </summary>
        internal static string Stats_GameTypeStatsDetail {
            get {
                return ResourceManager.GetString("Stats_GameTypeStatsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总览 的本地化字符串。
        /// </summary>
        internal static string Stats_Overview {
            get {
                return ResourceManager.GetString("Stats_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总游戏次数 的本地化字符串。
        /// </summary>
        internal static string Stats_TotalGames {
            get {
                return ResourceManager.GetString("Stats_TotalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总游戏次数 的本地化字符串。
        /// </summary>
        internal static string Stats_TotalGamesPlayed {
            get {
                return ResourceManager.GetString("Stats_TotalGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总胜利次数 的本地化字符串。
        /// </summary>
        internal static string Stats_TotalGamesWon {
            get {
                return ResourceManager.GetString("Stats_TotalGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总游戏时间 的本地化字符串。
        /// </summary>
        internal static string Stats_TotalPlayTime {
            get {
                return ResourceManager.GetString("Stats_TotalPlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总胜利次数 的本地化字符串。
        /// </summary>
        internal static string Stats_TotalWins {
            get {
                return ResourceManager.GetString("Stats_TotalWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胜率 的本地化字符串。
        /// </summary>
        internal static string Stats_WinRate {
            get {
                return ResourceManager.GetString("Stats_WinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胜利: {0} 的本地化字符串。
        /// </summary>
        internal static string Stats_Wins {
            get {
                return ResourceManager.GetString("Stats_Wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左下 的本地化字符串。
        /// </summary>
        internal static string SubGrid_BottomLeft {
            get {
                return ResourceManager.GetString("SubGrid_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右下 的本地化字符串。
        /// </summary>
        internal static string SubGrid_BottomRight {
            get {
                return ResourceManager.GetString("SubGrid_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中心 的本地化字符串。
        /// </summary>
        internal static string SubGrid_Center {
            get {
                return ResourceManager.GetString("SubGrid_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左上 的本地化字符串。
        /// </summary>
        internal static string SubGrid_TopLeft {
            get {
                return ResourceManager.GetString("SubGrid_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右上 的本地化字符串。
        /// </summary>
        internal static string SubGrid_TopRight {
            get {
                return ResourceManager.GetString("SubGrid_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 的本地化字符串。
        /// </summary>
        internal static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色 的本地化字符串。
        /// </summary>
        internal static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        internal static string Theme_System {
            get {
                return ResourceManager.GetString("Theme_System", resourceCulture);
            }
        }
    }
}
